let isEnglish = true;
switchLanguage();
function switchLanguage() {
    isEnglish = !isEnglish;
    const t = {
        it: {
            titolo: "Portfolio di Riccardo",
            sottotitolo: "Il mio viaggio tra studio, progetti e passioni",
            nav_materie: "Materie ▾",
            nav_info: "Informatica",
            nav_ia: "Intelligenza artificiale",
            nav_sis: "Sistemi e reti",
            nav_tpsit: "Tpsit",
            nav_ita: "Italiano",
            nav_storia: "Storia",
            nav_ing: "Inglese",
            nav_mate: "Matematica",
            nav_hobby: "Hobby",
            nav_pcto: "PCTO",
            nav_progetti: "Progetti ▾",
            nav_3: "Progetto 3° anno",
            nav_4: "Progetto 4° anno",
            nav_5: "Progetto 5° anno",
            nav_contatti: "Contatti",
            materie_titolo: "Materie",
            info_titolo: "Informatica",
            ia_titolo: "Intelligenza artificiale",
            sis_titolo: "Sistemi e reti",
            tpsit_titolo: "Tpsit",
            ita_titolo: "Italiano",
            storia_titolo: "Storia",
            ing_titolo: "Inglese",
            mate_titolo: "Matematica",
            info_text: "Ho imparato linguaggi per sviluppo web, HTML, CSS, PHP, JS e MySQL e per sviluppo app, C, C#, Java, Python, assembly. Ho realizzato gestionali, simulazioni web e giochi.",
            ia_text: "Ho studiato concetti base di intelligenza artificiale, come machine learning e reti neurali. Ho applicato questi concetti in progetti pratici.",
            sistemi_text: "Ho imparato a configurare reti, gestirne le comunicazioni con e senza NAT, a configurare server web, DHCP, FTP, posta e DNS.",
            tpsit: "Ho approfondito la progettazione del software passando ad android, e usando il Java ho creato delle prime semplici applicazioni.",
            ita: "Ho sviluppato capacità di analisi e produzione testuale e studiato autori e movimenti letterari.",
            storia: "Ho studiato eventi storici moderni e contemporanei, principalmente guerre mondiali.",
            ing: "Miglioramento della comprensione e produzione scritta e orale.",
            mate: "Ho studiato algebra, funzioni, limiti, derivate, integrali, probabilità e statistica.",
            hobby_competenze_titolo: "Competenze e hobby",
            hobby_titolo: "Hobby",
            hobby_text: "<li>Andare in bici</li><li>Basket</li><li>Anime e manga</li>",
            hard_skills_text: "HTML, CSS, PHP, JS, Git, database, C, C#, Java, Python, assembly.",
            soft_skills_text: "Problem solving, lavoro in team, comunicazione, adattabilità.",
            pcto_titolo: "PCTO",
            pcto_text: "<h3>PCTO presso APRA (Jesi)</h3><p>Attività di sviluppo web, test, debugging e collaborazione in team.</p>",
            section_progetti: "Progetti",
            proj3_titolo: "Terzo anno",
            proj3_text: "Scacchi - 2D in C#, grafica fatta con la libreria SFML. Focus sulla funzionalità.",
            proj4_titolo: "Quarto anno",
            proj4_text: "Plant vs Zombie – Clone 2D sviluppato in C# con logica di spawn, gestione HP e animazioni. Focus sul game loop.",
            proj5_titolo: "Quinto anno",
            proj5_text: "Gestionale scout - applicazione web sviluppata in gruppo con la classe, con backend in PHP e MySQL.",
            projhack_titolo: "Hackathon 2025 (quinto anno)",
            projhack_text: "Team da 6, progetto di un'app web per facilitare comunicazioni tra scuole, studenti, diplomati e aziende per PCTO, tirocini e lavoro.",
            contatti_titolo: "Contatti",
            diricts: "&copy; 2025 Riccardo Portfolio - Tutti i diritti riservati"
        },
        en: {
            titolo: "Riccardo's Portfolio",
            sottotitolo: "My journey through study, projects and passions",
            nav_materie: "Subjects ▾",
            nav_info: "Computer science",
            nav_ia: "Artificial intelligence",
            nav_sis: "Systems and networks",
            nav_tpsit: "Tpsit",
            nav_ita: "Italian",
            nav_storia: "History",
            nav_ing: "English",
            nav_mate: "Mathematics",
            nav_hobby: "Hobbies",
            nav_pcto: "Internship",
            nav_progetti: "Projects ▾",
            nav_3: "Project 3rd year",
            nav_4: "Project 4th year",
            nav_5: "Project 5th year",
            nav_contatti: "Contacts",
            materie_titolo: "Subjects",
            info_titolo: "Computer science",
            ia_titolo: "Artificial intelligence",
            sis_titolo: "Systems and networks",
            tpsit_titolo: "Tpsit",
            ita_titolo: "Italian",
            storia_titolo: "History",
            ing_titolo: "English",
            mate_titolo: "Mathematics",
            info_text: "I learned web dev languages like HTML, CSS, PHP, JS, MySQL and app dev ones like C, C#, Java, Python, and assembly. I built management apps, simulations, and games.",
            ia_text: "I studied base concepts of artificial intelligence, like machine learning and neural networks. I applied these concepts in practical projects.",
            sis_text: "I learned to configure networks, manage communications with/without NAT, and set up web, DHCP, FTP, mail, and DNS servers.",
            tpsit: "I further developed the design of software passing to android, and using Java I created some simple applications.",
            ita: "I developed the ability to analyze and produce text, and studied authors and literary movements.",
            storia: "I studied modern and contemporary historical events, mainly the World Wars.",
            ing: "Improvement of comprehension and production of written and oral communication.",
            mate: "I studied algebra, functions, limits, derivatives, integrals, probability, and statistics.",
            hobby_competenze_titolo: "Skills and hobbies",
            hobby_titolo: "Hobbies",
            hobby_text: "<li>Cycling</li><li>Basketball</li><li>Anime and manga</li>",
            hard_skills_text: "HTML, CSS, PHP, JS, Git, database, C, C#, Java, Python, assembly.",
            soft_skills_text: "Problem solving, teamwork, communication, adaptability.",
            pcto_titolo: "PCTO",
            pcto_text: "<h3>PCTO at APRA (Jesi)</h3><p>Web development, testing, debugging, and teamwork activities.</p>",
            section_progetti: "Projects",
            proj3_titolo: "Third year",
            proj3_text: "Chess - 2D in C# using SFML for graphics. Focus on functionality.",
            proj4_titolo: "Fourth year",
            proj4_text: "Plant vs Zombie – 2D clone made in C# with spawn logic, HP management and animations. Focus on game loop.",
            proj5_titolo: "Fifth year",
            proj5_text: "Scout manager - web app made with the class team, backend in PHP and MySQL.",
            projhack_titolo: "Hackathon 2025 (fifth year)",
            projhack_text: "Team of 6, web app project to connect schools, students, graduates and companies for internships and jobs.",
            contatti_titolo: "Contacts",
            diricts: "&copy; 2025 Riccardo Portfolio - All rights reserved"
        }
    };

    const lang = isEnglish ? t.en : t.it;
    for (let id in lang) {
        const el = document.getElementById(id);
        if (el) el.innerHTML = lang[id];
    }
}